### PR TITLE
build on ubuntu 14.04 and libusb version 0.1.12  some errors

### PR DESCRIPTION
**Pull request by ai0376**
_$mkdir build
$cd build
$ cmake ..
$make_
some errors:

1 ~/libusbnet/src/usbnet.c:758:5:error : conflicting types for 'usb_bulk_write'
 /usr/include/usb.h:304:5: note:previous declaration of 'usb_bulk_write' was here

### CODE REVIEW

**Comment by mjrao** [comment]
add comment

**Comment by vavrusa** [comment]
LGTM, thanks!
